version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: password_manager
      POSTGRES_PASSWORD: pwd

  web:
    build: .
    command: gunicorn password_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://password_manager:pwd@db:5432/password_manager
      RENDER_EXTERNAL_HOSTNAME: localhost

volumes:
  postgres_data:
