# Generated by Django 5.0.3 on 2024-03-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'password entries'},
        ),
        migrations.RenameField(
            model_name='passwordentry',
            old_name='encrypted_password',
            new_name='hashed_password',
        ),
    ]
