# Generated by Django 5.0.3 on 2024-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_passwordentry_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='hashed_password',
            new_name='password',
        ),
    ]
